name = "portfolio-1"
type = "webpack"
workers_dev = true
account_id = '175b312d511a64df3c0126e3c68e1f16'
route = "fayez-zouari.me"

[site]
bucket = "./build"
entry-point = "workers-site"

[env.production]
name = "portfolio-1"
workers_dev = false
route = "fayez-zouari.me"
